---
- hosts:  all
  gather_facts: 'true' 
  tasks:
    - name: gather facts from apps
      setup:
      register: find_output
    - file:
       path: /tmp/CMDB
       state: directory
      delegate_to: 10.211.55.9
    - copy:
       content: "{{ find_output }}"
       dest: /tmp/CMDB/{{ inventory_hostname }}
      delegate_to: 10.211.55.9
    - shell:
       "ansible-cmdb /tmp/CMDB/ > /var/www/html/overview.html"
      delegate_to: 10.211.55.9
