---
- hosts:  all
  gather_facts: 'true' 
  tasks:
    - name: gather facts from apps
      setup:
      register: find_output
    - local_action: copy content={{ find_output }} dest=./{{ inventory_hostname }}
